# Generated by Django 3.1 on 2020-08-07 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='styles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=50, null=True)),
                ('style', models.TextField(blank=True, null=True)),
                ('main', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sub', to='myapp.styles')),
            ],
        ),
        migrations.CreateModel(
            name='elements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(blank=True, max_length=20, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('src', models.URLField(blank=True, null=True)),
                ('style', models.TextField(blank=True, null=True)),
                ('main', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sub', to='myapp.elements')),
            ],
        ),
        migrations.CreateModel(
            name='components',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=50, null=True)),
                ('tag', models.CharField(blank=True, max_length=20, null=True)),
                ('text', models.TextField(blank=True)),
                ('src', models.URLField(blank=True, null=True)),
                ('style', models.TextField(blank=True, null=True)),
                ('main', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sub', to='myapp.components')),
            ],
        ),
    ]
