# Generated by Django 3.1 on 2020-08-12 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='components',
            name='src',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='elements',
            name='src',
            field=models.TextField(blank=True, null=True),
        ),
    ]
