# Generated by Django 3.1 on 2020-08-19 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20200817_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elements',
            name='style',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
