# Generated by Django 3.1 on 2020-09-05 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20200819_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='elements',
            name='table',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='styles',
            name='style',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
